---
driver:
  name: dokken
  privileged: true
  chef_version: 14
  cap_add:
    - CAP_MKNOD
  volumes:
    - /sys/fs/cgroup:/sys/fs/cgroup
    - /lib/modules:/lib/modules:ro
    - /run/openvswitch:/run/openvswitch

transport:
  name: dokken

provisioner:
  name: dokken
  encrypted_data_bag_secret_key_path: .chef/encrypted_data_bag_secret
  roles_path: roles
  environments_path: environments
  attributes:
    openstack:
      secret:
        key_path: /opt/kitchen/encrypted_data_bag_secret

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04
    driver:
      image: dokken/ubuntu-18.04
      pid_one_command: /bin/systemd
  - name: centos-7
    platform: rhel
    driver:
      image: dokken/centos-7
      pid_one_command: /usr/lib/systemd/systemd

suites:
  - name: default
    driver:
      ports:
        - '80'
        - '8080'
        - '443'
        - '3460'
        - '3306'
        - '5672'
        - '5000'
        - '35357'
        - '8774'
        - '8776'
        - '9292'
        - '9696'
        - '8000'
        - '8003'
        - '8004'
    run_list:
      - recipe[openstack_test]
      - role[allinone]
    provisioner:
      client_rb:
        environment: allinone
    verifier:
      inspec_tests:
        - test/tempest/default
    attributes:
      openstack:
        network:
          tun_network_bridge_interface: eth0
