- job:
    name: openstack-chef-delivery
    parent: base
    description: Run Chef Delivery tests with openstack-chef
    required-projects: openstack/openstack-chef
    pre-run: playbooks/pre-delivery.yaml
    run: playbooks/delivery.yaml
    timeout: 1800

- job:
    name: openstack-chef-integration
    parent: base
    description: Run integration tests with openstack-chef on Ubuntu Bionic
    required-projects: openstack/openstack-chef
    pre-run: playbooks/pre-integration.yaml
    run: playbooks/integration.yaml
    post-run: playbooks/post.yaml
    timeout: 5400

- project-template:
    name: openstack-chef-jobs
    check:
      jobs:
        - openstack-chef-delivery
        - openstack-chef-integration
    gate:
      jobs:
        - openstack-chef-delivery
        - openstack-chef-integration

- project:
    templates:
      - deploy-guide-jobs
      - publish-openstack-docs-pti
      - openstack-chef-jobs
