- hosts: all
  tasks:
    - name: run integration
      shell:
        cmd: /opt/chef/embedded/bin/rake integration
        chdir: '{{ ansible_user_dir }}/src/opendev.org/openstack/openstack-chef'
      environment:
        WORKSPACE: '{{ ansible_user_dir }}'
